"""Add_Extended_Models

Revision ID: 311e86fecc9e
Revises: ddb166051ea5
Create Date: 2026-02-10 13:45:01.353178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added for SQLModel support


# revision identifiers, used by Alembic.
revision: str = '311e86fecc9e'
down_revision: Union[str, None] = 'ddb166051ea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_fans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('size_mm', sa.Integer(), nullable=False),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('rgb', sa.Boolean(), nullable=False),
    sa.Column('noise_level_db', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id')
    )
    op.create_table('casings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('max_gpu_length_mm', sa.Integer(), nullable=False),
    sa.Column('max_cpu_cooler_height_mm', sa.Integer(), nullable=False),
    sa.Column('psu_support', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('form_factor_support', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id')
    )
    op.create_table('cpu_coolers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('cooler_type', sa.Enum('AIR', 'LIQUID', name='coolertype'), nullable=False),
    sa.Column('fan_size_mm', sa.Integer(), nullable=True),
    sa.Column('radiator_size_mm', sa.Integer(), nullable=True),
    sa.Column('tdp_capacity_watts', sa.Integer(), nullable=True),
    sa.Column('socket_support', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id')
    )
    op.create_table('laptops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('processor_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ram_gb', sa.Integer(), nullable=False),
    sa.Column('storage_gb', sa.Integer(), nullable=False),
    sa.Column('display_size_inch', sa.Float(), nullable=False),
    sa.Column('gpu_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('battery_capacity_wh', sa.Integer(), nullable=True),
    sa.Column('touch_screen', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id')
    )
    op.create_table('monitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('screen_size_inch', sa.Float(), nullable=False),
    sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_rate_hz', sa.Integer(), nullable=False),
    sa.Column('panel_type', sa.Enum('IPS', 'VA', 'TN', 'OLED', name='monitorpaneltype'), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('curved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id')
    )
    op.create_table('peripherals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('peripheral_type', sa.Enum('KEYBOARD', 'MOUSE', 'HEADPHONE', 'UPS', name='peripheraltype'), nullable=False),
    sa.Column('connection_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peripherals')
    op.drop_table('monitors')
    op.drop_table('laptops')
    op.drop_table('cpu_coolers')
    op.drop_table('casings')
    op.drop_table('case_fans')
    # ### end Alembic commands ###
