"""Initial_migration

Revision ID: d0ef8c674e43
Revises: 
Create Date: 2026-02-10 12:34:51.184607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added for SQLModel support


# revision identifiers, used by Alembic.
revision: str = 'd0ef8c674e43'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('component_type', sa.Enum('CPU', 'MOTHERBOARD', 'RAM', 'GPU', 'STORAGE', 'PSU', 'CASE', 'COOLER', name='componenttype'), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('performance_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_name'), 'components', ['name'], unique=False)
    op.create_index(op.f('ix_components_slug'), 'components', ['slug'], unique=True)
    op.create_table('cpus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('socket', sa.Enum('AM5', 'AM4', 'LGA1700', 'LGA1200', name='sockettype'), nullable=False),
    sa.Column('core_count', sa.Integer(), nullable=False),
    sa.Column('thread_count', sa.Integer(), nullable=False),
    sa.Column('base_clock_ghz', sa.Float(), nullable=False),
    sa.Column('boost_clock_ghz', sa.Float(), nullable=True),
    sa.Column('tdp', sa.Integer(), nullable=False),
    sa.Column('integrated_graphics', sa.Boolean(), nullable=False),
    sa.Column('igpu_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id')
    )
    op.create_table('motherboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('socket', sa.Enum('AM5', 'AM4', 'LGA1700', 'LGA1200', name='sockettype'), nullable=False),
    sa.Column('form_factor', sa.Enum('ATX', 'MICRO_ATX', 'MINI_ITX', 'E_ATX', name='formfactor'), nullable=False),
    sa.Column('ram_type', sa.Enum('DDR4', 'DDR5', name='ramtype'), nullable=False),
    sa.Column('ram_slots', sa.Integer(), nullable=False),
    sa.Column('max_ram_gb', sa.Integer(), nullable=False),
    sa.Column('chipset', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pcie_x16_slots', sa.Integer(), nullable=False),
    sa.Column('m2_slots', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id')
    )
    op.create_table('rams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('ram_type', sa.Enum('DDR4', 'DDR5', name='ramtype'), nullable=False),
    sa.Column('capacity_gb', sa.Integer(), nullable=False),
    sa.Column('speed_mhz', sa.Integer(), nullable=False),
    sa.Column('modules', sa.Integer(), nullable=False),
    sa.Column('cas_latency', sa.Integer(), nullable=True),
    sa.Column('rgb', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id')
    )
    op.create_table('vendor_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.Enum('STARTECH', 'RYANS', 'TECHLAND', 'UCC', 'SKYLAND', 'NEXUS', name='vendorname'), nullable=False),
    sa.Column('price_bdt', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_prices_component_id'), 'vendor_prices', ['component_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_prices_component_id'), table_name='vendor_prices')
    op.drop_table('vendor_prices')
    op.drop_table('rams')
    op.drop_table('motherboards')
    op.drop_table('cpus')
    op.drop_index(op.f('ix_components_slug'), table_name='components')
    op.drop_index(op.f('ix_components_name'), table_name='components')
    op.drop_table('components')
    # ### end Alembic commands ###
