"""Add_GPU_Storage_PSU

Revision ID: ddb166051ea5
Revises: d0ef8c674e43
Create Date: 2026-02-10 13:08:10.160846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added for SQLModel support


# revision identifiers, used by Alembic.
revision: str = 'ddb166051ea5'
down_revision: Union[str, None] = 'd0ef8c674e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('vram_gb', sa.Integer(), nullable=False),
    sa.Column('length_mm', sa.Integer(), nullable=False),
    sa.Column('recommended_psu_wattage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id')
    )
    op.create_table('psus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('wattage', sa.Integer(), nullable=False),
    sa.Column('efficiency_rating', sa.Enum('BRONZE', 'GOLD', 'PLATINUM', 'TITANIUM', 'WHITE', 'NONE', name='psukb'), nullable=False),
    sa.Column('modular', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id')
    )
    op.create_table('storages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('storage_type', sa.Enum('NVME', 'SATA', 'HDD', name='storagetype'), nullable=False),
    sa.Column('capacity_gb', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storages')
    op.drop_table('psus')
    op.drop_table('gpus')
    # ### end Alembic commands ###
