"""Add raw_data to vendor_prices

Revision ID: f221f422eb90
Revises: 311e86fecc9e
Create Date: 2026-02-13 14:57:34.266896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added for SQLModel support


# revision identifiers, used by Alembic.
revision: str = 'f221f422eb90'
down_revision: Union[str, None] = '311e86fecc9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_prices', sa.Column('raw_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_prices', 'raw_data')
    # ### end Alembic commands ###
